### ISSUE TITLE
accentuation beug

### ISSUE THREAD

**Issue by rolandbouzet** [bitfocus/companion-module-irisdown-countdowntimer#4]
![stream deck](https://user-images.githubusercontent.com/54640685/69482445-c4fc5b00-0e1b-11ea-9e5d-024127d071af.PNG)
Bonjour, 

Quand on créer une tâche : coutdown : message text,  on ne peut pas mettre les accents grave et aiguë. Dans le logiciel il y as des points d’interrogations qui se mettent.  

Hello,

When you create a task: coutdown: message text, you can not put the bass and treble accents. In the software there are question marks that get started.

**Comment by DaveShep** [comment]
Encoding changed to UTF8 in Irisdown Countdown Timer v2.0.12

ok to close

**Comment by krocheck** [comment]
thanks!
