### ISSUE TITLE
Missing line terminator in string

### ISSUE THREAD

**Issue by DaveShep** [bitfocus/companion-module-irisdown-countdowntimer#6]
https://github.com/bitfocus/companion-module-irisdown-countdowntimer/blob/bf86829a677a5adbee130c93cc9c916470897125/index.js#L235

should read

`this.socket.send("UPDATEMODE 2\r\n");`

**Comment by DaveShep** [comment]
No other issues found

**Comment by krocheck** [comment]
copy
